version: "3.8"

services:

  user-svc:
    image: nusrat215/user_svc:v1
    env_file:
      - ./user_service/.env
    networks:
      - smartlibrary
    ports:
      - "8081:8081"
    depends_on:
      - user-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  book-svc:
    image: nusrat215/book_svc:v1
    env_file:
      - ./book_service/.env
    networks:
      - smartlibrary
    ports:
      - "8082:8082"
    depends_on:
      - book-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  loan-svc:
    image: nusrat215/loan_svc:v1
    env_file:
      - ./loan_service/.env
    networks:
      - smartlibrary
    ports:
      - "8083:8083"
    depends_on:
      - loan-db
      - user-svc
      - book-svc
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nusrat215/nginx_svc:v1
    ports:
      - "80:80"
    depends_on:
      - user-svc
      - book-svc
      - loan-svc
    networks:
      - smartlibrary
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - smartlibrary
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  user-db: 
    image: mysql:8
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=smart_library_user_db
    ports:
      - "3307:3306"
    volumes:
      - user_data:/var/lib/mysql
      - ./user_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smartlibrary
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  book-db: 
    image: mysql:8
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=smart_library_book_db
    ports:
      - "3308:3306"
    volumes:
      - book_data:/var/lib/mysql
      - ./book_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smartlibrary
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  loan-db: 
    image: mysql:8
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=smart_library_loan_db
    ports:
      - "3309:3306"
    volumes:
      - loan_data:/var/lib/mysql
      - ./loan_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smartlibrary
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  smartlibrary:
    driver: overlay
    
volumes:
  user_data:
  book_data:
  loan_data:
